import { ModalProvider } from "@context/ModalContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return <ModalProvider>{children}</ModalProvider>;
}
