import "@styles/globals.css";
import { UserProvider } from "@context/UserContext";
import { getCookies } from "@/app/server/cookies";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const user = (await getCookies("user")) || {};

    return (
        <html lang="en">
            <body>
                <UserProvider initialUser={user}>{children}</UserProvider>
            </body>
        </html>
    );
}
