import "@styles/globals.css";
import Navbar from "@components/navbar";
import Modals from "@components/modal";
import { Toaster } from "react-hot-toast";
import { ModalProvider } from "@context/ModalContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ModalProvider>
                    <Navbar />
                    <Toaster />
                    {children}
                    <Modals />
                </ModalProvider>
            </body>
        </html>
    );
}
