import Navbar from "@components/navbar";
import Modals from "@components/modal";
import { Toaster } from "react-hot-toast";
import { ModalProvider } from "@context/ModalContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ModalProvider>
            <Navbar />
            <Toaster />
            {children}
            <Modals />
        </ModalProvider>
    );
}
